preview = true
line-length = 120

[lint]
select = [
   "ALL"
]
ignore = [
   "CPY",     # recommend copyright notice
   "DOC",     # recommend docstrings
   "RET504",  # recommend not assigning right before returning
   "T20",     # recommend removal of print statements
]

[lint.pydocstyle]
convention = "pep257"