preview = true
line-length = 120

[lint]
select = [
   "ALL"
]
ignore = [
   "ANN",     # recommend type annotations
   "CPY",     # recommend copyright notice
   "D",       # recommend docstrings
   "DOC",     # recommend docstrings
   "RET504",  # recommend not assigning right before returning
   "T20",     # recommend removal of print statements
]